version: "3"
services:
  waf:
    image: wafaas-env:latest
    build:
      context: .
    container_name: lb4-dev-container
    command: ["bash", "-c", "while true; do sleep 1; done"]
 
    volumes:
      - /Users/zong/Works/4.2018.07.16-Coding-Test/ts/src/zz.verifications/lb4:/root/app_dir
    ports:
      - 3000:3000

